apiVersion: v1
kind: Service
metadata:
  name: backend
spec:
  selector:
    app: backend
  ports:
    - protocol: TCP
      port: 3000
      targetPort: 3000
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      containers:
        - name: backend
          image: mmalach/todo-backend:v1
          build:
            context: ./backend
            dockerfile: Dockerfile
          ports:
            - containerPort: 3000
          env:
            - name: DBUSER
              value: postgres
            - name: DBHOST
              value: database
            - name: DBDATABASE
              value: postgres
            - name: DBPORT
              value: "5432"
      restartPolicy: Always