apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: database-pvc
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
---
apiVersion: v1
kind: Service
metadata:
  name: database
spec:
  selector:
    app: database
  ports:
    - protocol: TCP
      port: 5432
      targetPort: 5432
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: database
spec:
  replicas: 1
  selector:
    matchLabels:
      app: database
  template:
    metadata:
      labels:
        app: database
    spec:
      containers:
        - name: database
          image: docker.io/bitnami/postgresql:15
          env:
            - name: ALLOW_EMPTY_PASSWORD
              value: "yes"
            - name: POSTGRESQL_USERNAME
              value: "postgres"
            - name: POSTGRESQL_DATABASE
              value: "postgres"
          ports:
            - containerPort: 5432
          volumeMounts:
            - name: database-volume
              mountPath: /bitnami/postgresql
            - name: init-scripts
              mountPath: /docker-entrypoint-initdb.d
      volumes:
        - name: database-volume
          persistentVolumeClaim:
            claimName: database-pvc
        - name: init-scripts
          hostPath:
            path: ./database/scripts
      restartPolicy: Always