apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: database-pvc
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
---
apiVersion: v1
kind: Service
metadata:
  name: backend
spec:
  selector:
    app: backend
  ports:
    - protocol: TCP
      port: 3000
      targetPort: 3000
---
apiVersion: v1
kind: Service
metadata:
  name: database
spec:
  selector:
    app: database
  ports:
    - protocol: TCP
      port: 5432
      targetPort: 5432
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      containers:
        - name: backend
          image: mmalach/todo-backend:v1
          build:
            context: ./backend
            dockerfile: Dockerfile
          ports:
            - containerPort: 3000
          env:
            - name: DBUSER
              value: postgres
            - name: DBHOST
              value: database
            - name: DBDATABASE
              value: postgres
            - name: DBPORT
              value: "5432"
      restartPolicy: Always
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: database
spec:
  replicas: 1
  selector:
    matchLabels:
      app: database
  template:
    metadata:
      labels:
        app: database
    spec:
      containers:
        - name: database
          image: docker.io/bitnami/postgresql:15
          env:
            - name: ALLOW_EMPTY_PASSWORD
              value: "yes"
            - name: POSTGRESQL_USERNAME
              value: "postgres"
            - name: POSTGRESQL_DATABASE
              value: "postgres"
          ports:
            - containerPort: 5432
          volumeMounts:
            - name: database-volume
              mountPath: /bitnami/postgresql
            - name: init-scripts
              mountPath: /docker-entrypoint-initdb.d  # Volume-Mount für die Initialisierungsskripte hinzugefügt
      volumes:
        - name: database-volume
          persistentVolumeClaim:
            claimName: database-pvc
        - name: init-scripts
          hostPath:
            path: ./database/scripts   # Anpassen des Pfads zu deinen Skripten auf dem Host-System
      restartPolicy: Always
