version: '3.8'

services:
  backend:
    build: ./backend
    ports:
      - "3000:3000"
    environment:
      DBUSER: postgres
      DBHOST: database
      DBDATABASE: postgres
      DBPORT: 5432
    restart: always
    depends_on:
      - database
  database:
    image: docker.io/bitnami/postgresql:15
    environment:
      ALLOW_EMPTY_PASSWORD: 'yes'
      POSTGRESQL_USERNAME: 'postgres'
      POSTGRESQL_DATABASE: 'postgres'
    ports:
      - "5432:5432"
    volumes:
      - 'database:/bitnami/postgresql'
      - ./database/scripts:/docker-entrypoint-initdb.d
    restart: always
volumes:
  database:
    driver: local
