version: '3.8'

services:
  backend:
    build: ./backend
    ports:
      - "3000:3000"
    restart: always
    depends_on:
      - database
  database:
    build: ./database
    ports:
      - "5432:5432"
    volumes:
      - 'database:/bitnami/postgresql'
    restart: always
  frontend:
    build:
      context: ./frontend
      args:
        - API_URL=http://localhost:3000
    ports:
      - "8080:8080"
    restart: always
    depends_on:
      - database
      - backend
volumes:
  database:
    driver: local
