version: '3.8'

services:
  backend:
    build: ./backend
    ports:
      - "3000:3000"
    environemnt:
      - DBUSER=postgres
      - DBHOST=database
      - DBDATABASE=postgres
      - DBPORT=5432
    restart: always
    depends_on:
      - database
  database:
    build: ./database
    ports:
      - "5432:5432"
    environment:
      - POSTGRESQL_USERNAME=postgres
      - POSTGRESQL_DATABASE=postgres
    volumes:
      - 'database:/bitnami/postgresql'
    restart: always
volumes:
  database:
    driver: local
